name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - run: echo "git clone https://github.com/univdev/recommends"
      - run: git clone https://github.com/univdev/recommends
      - run: echo "ls"
      - run: ls