name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: recommends 레포지토리 클론
        run: git clone https://github.com/univdev/recommends
      - name: recommends 폴더 구조 출력
        working-directory: ./recommends
        run: ls -f
      - name: test.txt 파일 추가
        working-directory: ./recommends
        run: touch test.txt
      - name: git 정보 설정
        working-directory: ./recommends
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"
      - name: 파일을 깃에 추가
        working-directory: ./recommends
        run: git add *
      - name: 커밋 추가
        working-directory: ./recommends
        run: git commit -m "text.txt 파일 추가"
      - name: 레포지토리 푸시
        working-directory: ./recommends
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN }}